workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 30
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -scheme TappyVerse \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/TappyVerse.xcarchive \
            clean archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/TappyVerse.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
